package com.creatorops.activity.entity;

/**
 * Defines the types of events that can be recorded in the activity log timeline.
 */
public enum EventType {
    CONTENT_CREATED,
    CONTENT_UPDATED,
    CONTENT_DELETED,
    RESEARCH_CREATED,
    RESEARCH_UPDATED,
    RESEARCH_DELETED,
    SCRIPT_CREATED,
    SCRIPT_UPDATED,
    SCRIPT_DELETED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_UPDATED,
    ASSIGNMENT_STATUS_CHANGED,
    ASSIGNMENT_DELETED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,
    ASSET_CREATED,
    ASSET_UPDATED,
    ASSET_DELETED,
    CONTENT_SCHEDULED,
    CONTENT_RESCHEDULED,
    CONTENT_PUBLISHED,
    AI_BRAINSTORM_GENERATED,
    AI_SCRIPT_GENERATED
}

